# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: renatio.dynamicpdf::lang.layout.menu_label

# Model Form Field configuration
form: $/renatio/dynamicpdf/models/layout/fields.yaml

# Model Class name
modelClass: Renatio\DynamicPDF\Models\Layout

# Default redirect location
defaultRedirect: renatio/dynamicpdf/templates/index/layouts

# Create page
create:
    title: renatio.dynamicpdf::lang.layout.create_layout
    redirect: renatio/dynamicpdf/layouts/update/:id
    redirectClose: renatio/dynamicpdf/templates/index/layouts

# Update page
update:
    title: renatio.dynamicpdf::lang.layout.edit_layout
    redirect: renatio/dynamicpdf/templates/index/layouts
    redirectClose: renatio/dynamicpdf/templates/index/layouts

# Preview page
preview:
    title: renatio.dynamicpdf::lang.templates.preview_html